<template>
  <div class="home">
    <button @click="logout">Logout</button>
    <button @click="newPost">New post</button>
    <ul>
      <li v-for="post in posts" :key="post.sha" @click="openFile(post.path)">
        {{ post.name }}
        <button @click="deletePost(post.path, post.sha)">Delete</button>
      </li>
    </ul>
    <input v-model="postData.title" />
    <input type="datetime-local" v-model="postData.date" />
    <vue-simplemde v-model="postContent" />
    <button @click="save">Save</button>
  </div>
</template>

<script>
import { Octokit } from "@octokit/rest";
import VueSimplemde from "vue-simplemde";
import matter from "gray-matter";

export default {
  name: "Home",
  components: { VueSimplemde },
  created: async function() {
    this.octokit = new Octokit({
      auth: this.pat
    });
    await this.listFiles();
  },
  data: function() {
    return {
      octokit: {},
      posts: [],
      postPath: "",
      postSha: "",
      postData: {
        title: "",
        date: new Date()
      },
      postContent: ""
    };
  },
  computed: {
    owner() {
      return this.$store.state.owner;
    },
    repo() {
      return this.$store.state.repo;
    },
    pat() {
      return this.$store.state.pat;
    }
  },
  methods: {
    logout: function() {
      this.$store.commit("logout");
      this.$router.push({ name: "Login" });
    },
    newPost: function() {
      this.postPath = "";
      this.postSha = "";
      this.postData = {
        title: "",
        date: new Date()
      };
      this.postContent = "";
    },
    listFiles: async function() {
      const result = await this.octokit.repos.getContents({
        owner: this.owner,
        repo: this.repo,
        path: "_posts"
      });
      console.log(result);
      this.posts = result.data;
    },
    openFile: async function(postPath) {
      this.postPath = postPath;
      const result = await this.octokit.repos.getContents({
        owner: this.owner,
        repo: this.repo,
        path: this.postPath
      });
      // console.log(result);
      this.postSha = result.data.sha;
      const content = this.b64DecodeUnicode(result.data.content);
      const fm = matter(content);
      this.postData = fm.data;
      this.postContent = fm.content;
    },
    b64EncodeUnicode: function(str) {
      return btoa(
        encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, function(match, p1) {
          return String.fromCharCode(parseInt(p1, 16));
        })
      );
    },
    b64DecodeUnicode: function(str) {
      return decodeURIComponent(
        Array.prototype.map
          .call(atob(str), function(c) {
            return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
          })
          .join("")
      );
    },
    save: async function() {
      if (this.postContent === "") {
        return;
      }
      // Generate path for new post
      if (this.postSha === "") {
        this.postPath = `_posts/${this.postData.date
          .toISOString()
          .slice(0, 10)}-${this.postData.title
          .toLowerCase()
          .split(" ")
          .join("-")}.md`;
      }
      const result = await this.octokit.repos.createOrUpdateFile({
        owner: this.owner,
        repo: this.repo,
        path: this.postPath,
        message: "Commit generated by github-cms",
        content: this.b64EncodeUnicode(
          matter.stringify(this.postContent, this.postData)
        ),
        sha: this.postSha
      });
      console.log(result);
    },
    deletePost: async function(path, sha) {
      const result = await this.octokit.repos.deleteFile({
        owner: this.owner,
        repo: this.repo,
        path: path,
        message: "Commit generated by github-cms",
        sha: sha
      });
      console.log(result);
    }
  }
};
</script>

<style scoped>
@import "~simplemde/dist/simplemde.min.css";
</style>
