<template>
  <div class="home">
    <ul>
      <li v-for="post in posts" :key="post" @click="openFile(post)">
        {{ post }}
      </li>
    </ul>
    <textarea v-model="currentPost"></textarea>
    <button @click="save">Save</button>
  </div>
</template>

<script>
import { Octokit } from "@octokit/rest";
export default {
  name: "Home",
  components: {},
  created: async function() {
    this.octokit = new Octokit({
      auth: this.pat
    });
    await this.listFiles();
  },
  data: function() {
    return {
      pat: process.env.VUE_APP_PAT,
      owner: process.env.VUE_APP_OWNER,
      repo: process.env.VUE_APP_REPO,
      octokit: {},
      posts: [],
      currentPostPath: "",
      currentPostSha: "",
      currentPost: ""
    };
  },
  methods: {
    listFiles: async function() {
      const result = await this.octokit.repos.getContents({
        owner: this.owner,
        repo: this.repo,
        path: "_posts"
      });
      // console.log(result);
      this.posts = result.data.map(x => x.path);
    },
    openFile: async function(postPath) {
      this.currentPostPath = postPath;
      const result = await this.octokit.repos.getContents({
        owner: this.owner,
        repo: this.repo,
        path: this.currentPostPath
      });
      console.log(result);
      this.currentPostSha = result.data.sha;
      this.currentPost = this.b64DecodeUnicode(result.data.content);
    },
    b64EncodeUnicode: function(str) {
      return btoa(
        encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, function(match, p1) {
          return String.fromCharCode(parseInt(p1, 16));
        })
      );
    },
    b64DecodeUnicode: function(str) {
      return decodeURIComponent(
        Array.prototype.map
          .call(atob(str), function(c) {
            return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
          })
          .join("")
      );
    },
    save: async function() {
      if (this.currentPost === "") {
        return;
      }
      const result = await this.octokit.repos.createOrUpdateFile({
        owner: this.owner,
        repo: this.repo,
        path: this.currentPostPath,
        message: "Commit generated by github-cms",
        content: this.b64EncodeUnicode(this.currentPost),
        sha: this.currentPostSha
      });
      console.log(result);
    }
  }
};
</script>
