<template>
  <div class="home">
    <ul>
      <li v-for="post in posts" :key="post" @click="openFile(post)">
        {{ post }}
      </li>
    </ul>
    <input v-model="postData.title" />
    <input type="datetime-local" v-model="postData.date" />
    <vue-simplemde v-model="postContent" />
    <button @click="save">Save</button>
  </div>
</template>

<script>
import { Octokit } from "@octokit/rest";
import VueSimplemde from "vue-simplemde";
import matter from "gray-matter";

export default {
  name: "Home",
  components: { VueSimplemde },
  created: async function() {
    this.octokit = new Octokit({
      auth: this.pat,
    });
    await this.listFiles();
  },
  data: function() {
    return {
      pat: process.env.VUE_APP_PAT,
      owner: process.env.VUE_APP_OWNER,
      repo: process.env.VUE_APP_REPO,
      octokit: {},
      posts: [],
      postPath: "",
      postSha: "",
      postData: {
        title: "",
        date: new Date(),
      },
      postContent: "",
    };
  },
  methods: {
    listFiles: async function() {
      const result = await this.octokit.repos.getContents({
        owner: this.owner,
        repo: this.repo,
        path: "_posts",
      });
      // console.log(result);
      this.posts = result.data.map((x) => x.path);
    },
    openFile: async function(postPath) {
      this.postPath = postPath;
      const result = await this.octokit.repos.getContents({
        owner: this.owner,
        repo: this.repo,
        path: this.postPath,
      });
      // console.log(result);
      this.postSha = result.data.sha;
      const content = this.b64DecodeUnicode(result.data.content);
      const fm = matter(content);
      this.postData = fm.data;
      this.postContent = fm.content;
      console.log();
    },
    b64EncodeUnicode: function(str) {
      return btoa(
        encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, function(match, p1) {
          return String.fromCharCode(parseInt(p1, 16));
        })
      );
    },
    b64DecodeUnicode: function(str) {
      return decodeURIComponent(
        Array.prototype.map
          .call(atob(str), function(c) {
            return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
          })
          .join("")
      );
    },
    save: async function() {
      if (this.postContent === "") {
        return;
      }
      const result = await this.octokit.repos.createOrUpdateFile({
        owner: this.owner,
        repo: this.repo,
        path: this.postPath,
        message: "Commit generated by github-cms",
        content: this.b64EncodeUnicode(
          matter.stringify(this.postContent, this.postData)
        ),
        sha: this.postSha,
      });
      console.log(result);
    },
  },
};
</script>

<style scoped>
@import "~simplemde/dist/simplemde.min.css";
</style>
